
CREATE TABLE IF NOT EXISTS games (
    game_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    AppID TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS saves (
    save_id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    save_path TEXT NOT NULL,
    backup_path TEXT NOT NULL,
    save_name TEXT,
    save_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);
